### ISSUE TITLE
Return total number of rows in result

### ISSUE THREAD

**Issue by kghose** [CancerDataAggregator/cda-service#14]
bigquery has a built in way to provide the total number of rows for a query, regardless of how many rows were returned due to LIMIT.
https://cloud.google.com/bigquery/docs/samples/bigquery-query-total-rows

**Comment by kghose** [comment]
We might have to change where we apply offset and limit.

**Comment by pshapiro4broad** [comment]
> We might have to change where we apply offset and limit.

Yes, if we want to use the BQ `getTotalRows()` API, we'd have to use the BQ API for pagination instead of using SQL pagination. I'm not sure how well `offset` would perform in that case; there's no API to skip to a specific page, so the code would have loop over the `next page` API to get to a specific page. It's not clear from the BQ documentation if that would fetch each page, or if the fetch is deferred until the contents are requested.

Alternatively, we could do a separate query that uses `COUNT` to generate the total number of rows.

**Comment by YeastCell** [comment]
@pshapiro4broad are we still considering `COUNT` solution? Are there any cons? Is it a big deal that we'll have an additional query?

**Comment by pshapiro4broad** [comment]
I think using `COUNT` would be good enough for now. In the long term we may want to switch to using BQ pagination APIs and also change to a job/poll model for query processing. But COUNT shouldn't add a huge amount of overhead to the API.

**Comment by pshapiro4broad** [comment]
After testing, `COUNT` ended up having a high overhead in some cases, so I'm working on adding this using BQ pagination.
